# Generated by Django 3.2.6 on 2022-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
